### ISSUE TITLE
Some questions/help

### ISSUE THREAD

**Issue by andress134** [devgianlu/cloudflare-bypass#13]
so I try to generate web traffic on a voting site, but it seems that my requests are not sent, although your script shows me that it collects data
what's wrong, can you help me?
```js
const CloudflareBypass = require('./index')
const vote = process.argv[2];

function send_req() {

const cld = new CloudflareBypass(vote) //
cld.request().then((result) => {
	console.log('DONE!', result)
}).catch((err) => {
	console.error(err)
});
}

setInterval(() => {
    send_req(vote);
});
```

thank

**Comment by devgianlu** [comment]
The library is still under development and isn't able to bypass Cloudflare yet. All the traffic is being redirected to their servers.

**Comment by andress134** [comment]
> The library is still under development and isn't able to bypass Cloudflare yet. All the traffic is being redirected to their servers.

I just want to ask you, do you think this library will be able to bypass cloudflare in the future?

**Comment by devgianlu** [comment]
Yes, that's the objective, but I cannot provide any deadline.
