### ISSUE TITLE
The service is not running, and an error is reported

### ISSUE THREAD

**Issue by developer-wlj** [devgianlu/cloudflare-bypass#26]
I'm a beginner, I don't know how to use node, I followed the documentation and entered the command 3 times,
npm ci
npm run build --if-present
npm test
error 
echo "Error: no test specified" && exit 0
"Error: no test specified"

**Comment by devgianlu** [comment]
There is no file to execute. Just edit `test.js` and then execute `node test.js`. Beware that this library is not working.
