### ISSUE TITLE
Some help if is posible

### ISSUE THREAD

**Issue by andress134** [devgianlu/cloudflare-bypass#4]
Hello sir @devgianlu, can you help me to upgprade my script using your lib ? this is my original script

```js
const cloudscraper = require('cloudscraper');
const vote = process.argv[2];
function send_req() {

  return new Promise((resolve, reject) => {
    cloudscraper(vote, {
      cloudflareRetry: 10
    }) 
      .then(response => {
        resolve(response);
      })
      .catch(error => {
      return reject(error);
      });
  });
}

setInterval(() => {
    send_req();
});
```

Here is my test script but  some wrong

```js
const CloudflareBypass = require('./index');
const vote = process.argv[2];
function send_req() {

  return new Promise((resolve, reject) => {
    const cld = new CloudflareBypass(vote, {
      cloudflareRetry: 10
    }) 
      .then(response => {
        resolve(response);
      })
      .catch(err => {
      return reject(error);
      });
  });
}

setInterval(() => {
    send_req();
});
```

Thank

**Comment by devgianlu** [comment]
The library isn't ready just yet, there are still some issues with captchas. I'll also write the documentation afterwards.

**Comment by andress134** [comment]
> The library isn't ready just yet, there are still some issues with captchas. I'll also write the documentation afterwards.
> 
> Anyway, you can have a look at the `test.js` file.

not posible to make the lib like this https://github.com/JimmyLaurent/hcaptcha-solver ? or other option without puppeteer ?
using puppeteer is bad, use much cpu etc, just im try to make a script for vote based your lib, my server is jus spamming cpu and ram

**Comment by devgianlu** [comment]
This library just tries to solve captcha challenges by selecting random images. It is not very efficient.

BTW, I am planning to further optimize the library to avoid getting the captcha in the first place.

**Comment by AlfredoDaAs** [comment]
can this replace hooman library ?

**Comment by devgianlu** [comment]
@AlfredoDaAs Could you send a link?

**Comment by AlfredoDaAs** [comment]
> @AlfredoDaAs Could you send a link?

sure, [hooman](https://github.com/sayem314/hooman)

**Comment by devgianlu** [comment]
Yes, in its final form it should be able to.

**Comment by devgianlu** [comment]
Closing for now.
