### ISSUE TITLE
Running this on Unix

### ISSUE THREAD

**Issue by lmaochen** [devgianlu/cloudflare-bypass#5]
Is it possible to run this on Unix without a GPU?

**Comment by devgianlu** [comment]
As long as the only way to solve captcha is with puppeteer I'd say no. In the feature I'll add other captcha providers.

**Comment by lmaochen** [comment]
> As long as the only way to solve captcha is with puppeteer I'd say no. In the future I'll add other captcha providers.

Amazing, thank you. Is it possible to have a option to not use puppeteer and only solve the iUAM?

**Comment by devgianlu** [comment]
Right now, the library isn't able to solve the challenge without the captcha because, to Cloudflare, there's something suspicious. Will eventually add a captcha-fail feature in the future.
