### ISSUE TITLE
"Error: Bad challenge response: 400"

### ISSUE THREAD

**Issue by maliayas** [devgianlu/cloudflare-bypass#6]
I was testing the tool [on a site](https://paribu.com) and got this error. Since you can easily reproduce (I assume) I'm not adding logs. If needed just tell.

Promising library, thanks for sharing.

**Comment by devgianlu** [comment]
That's common unluckily. I know for sure that all challenges are able to be solved correctly, but sometimes they are not accepted. Figuring out which ones does this will be a pain.

**Comment by maliayas** [comment]
So even if we submit the correct challenge response, CF may reject it? I undertand the pain you mean, this kind of debugging is hard. Hope we find a way around the heuristics CF uses.

**Comment by devgianlu** [comment]
> So even if we submit the correct challenge response, CF may reject it?

Yes, it is probably because the challenge response may be incorrect sometimes and correct others.

**Comment by devgianlu** [comment]
I am closing this as it is a very common and generic issue.
